language: node_js
sudo: required
services:
  - docker

before_install:
  - docker build -t poltronieri/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true poltronieri/docker-react npm run test